### ISSUE TITLE
Clock In/Clock Out button

### ISSUE THREAD

**Issue by kernelpop** [CSUF-Computer-Science/super-duper-spork#29]
Attempting to clock in returned the following error

Request Method: | POST
-- | --
http://127.0.0.1:8000/employees/
2.1.2
IntegrityError
NOT NULL constraint failed: backend_shift.time_out
/home/df/.local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in execute, line 296
/usr/bin/python3
3.6.6
['/home/df/Documents/school/softeng/super-duper-spork/sporkify',  '/opt/ros/melodic/lib/python2.7/dist-packages',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/df/.local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Wed, 24 Oct 2018 03:57:06 +0000

**Comment by joshuaferrara** [comment]
Hmm I remember running into this while I was testing it. Can't recall what
triggered this. Will need to mess with it again. Try running your
migrations.

**Comment by kernelpop** [comment]
Ah yes, good ole migrations.
